language: scala
jdk:
  - openjdk8
before_install:
  - git fetch --tags
stages:
  - name: CI
  - name: publish
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    - name: CI
      script: ./sbt ci
    # run ci-release only if previous stages passed
    - stage: publish
      script: ./sbt ci-release
before_cache:
  - rm -fv $HOME/.ivy2/local/com.avast.grpc
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
